/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/mynhFgZ7rsK
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function Cek() {
  return (
    <div className="grid h-screen bg-gray-100 md:bg-transparent md:h-auto /deep/ grid-cols-[1fr] gap-0 md:grid-rows-[auto_1fr] md:grid-cols-[200px_1fr]">
      <div className="hidden md:flex flex-col w-full border-r border-gray-200 px-2 py-4 md:dark:border-gray-800 md:gap-4">
      </div>
      <div className="flex flex-col min-h-0 min-w-0 w-full">
        <header className="flex items-center border-b border-gray-200 px-4 py-2 md:hidden justify-between gap-4 dark:border-gray-800">
          <Button className="rounded-lg" size="icon" variant="ghost">
            <ChevronLeftIcon className="w-6 h-6" />
            <span className="sr-only">Back</span>
          </Button>
          <h1 className="text-lg font-semibold">Inbox</h1>
          <Button className="rounded-lg" size="icon" variant="ghost">
          
            <span className="sr-only">Search</span>
          </Button>
        </header>
        <main className="flex flex-col min-h-0 min-w-0">
          <div className="grid gap-2">
            <article className="flex flex-col items-start gap-2 rounded-lg border border-gray-200 p-3 text-left text-sm transition-all hover:bg-gray-100 dark:border-gray-800 dark:hover:bg-gray-800">
              <div className="flex items-center w-full">
                <div className="font-semibold">Emily Davis</div>
                <div className="ml-auto text-xs text-gray-500 dark:text-gray-400">2 days ago</div>
              </div>
              <div className="text-xs font-medium">Re: New order #34562</div>
              <div className="line-clamp-2 text-xs text-gray-500 dark:text-gray-400">
                Hi Emily, Thanks for your order. We are pleased to inform you that your order has been shipped. You can
                track your order online on our website. Please find the tracking number below.
              </div>
            </article>
           
          </div>
        </main>
      </div>
    </div>
  )
}


function InboxIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="22 12 16 12 14 15 10 15 8 12 2 12" />
      <path d="M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z" />
    </svg>
  )
}


function FileIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
      <polyline points="14 2 14 8 20 8" />
    </svg>
  )
}




function ChevronLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


